version: 1.0.{build}
build_script:
- ps: .\src\build\bl.ps1 -gitBranch $env:APPVEYOR_REPO_BRANCH -buildEnv appveyor
test: off
deploy: off
clone_depth: 20
deploy:
  provider: NuGet
  api_key:
    secure: hASCSp95jpkZYxTjTr8CFdMoWJEbgZDnr4Rle0k1aHlvgz+i5KZVp92ylzqgCXzC
  skip_symbols: true
  artifact: /.*\.nupkg/